// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask() {
  return window['go']['main']['App']['CancelTask']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckYtDlpUpdate() {
  return window['go']['main']['App']['CheckYtDlpUpdate']();
}

export function GetAIModels(arg1, arg2) {
  return window['go']['main']['App']['GetAIModels'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetStartupDiagnostics() {
  return window['go']['main']['App']['GetStartupDiagnostics']();
}

export function OpenOllamaModelLibrary() {
  return window['go']['main']['App']['OpenOllamaModelLibrary']();
}

export function ReadClipboardText() {
  return window['go']['main']['App']['ReadClipboardText']();
}

export function SelectModelPath() {
  return window['go']['main']['App']['SelectModelPath']();
}

export function SelectVaultPath() {
  return window['go']['main']['App']['SelectVaultPath']();
}

export function StartOllamaService() {
  return window['go']['main']['App']['StartOllamaService']();
}

export function StopOllamaService() {
  return window['go']['main']['App']['StopOllamaService']();
}

export function SubmitTask(arg1, arg2) {
  return window['go']['main']['App']['SubmitTask'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateModelPath(arg1) {
  return window['go']['main']['App']['UpdateModelPath'](arg1);
}

export function UpdateOpenAIKey(arg1) {
  return window['go']['main']['App']['UpdateOpenAIKey'](arg1);
}

export function UpdateVaultPath(arg1) {
  return window['go']['main']['App']['UpdateVaultPath'](arg1);
}
