// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CancelTask():Promise<void>;

export function CheckDependencies():Promise<main.DependencyStatus>;

export function GetAIModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetConfigPath():Promise<string>;

export function GetStartupDiagnostics():Promise<main.StartupDiagnostics>;

export function OpenOllamaModelLibrary():Promise<string>;

export function ReadClipboardText():Promise<string>;

export function SelectModelPath():Promise<string>;

export function SelectVaultPath():Promise<string>;

export function StartOllamaService():Promise<string>;

export function StopOllamaService():Promise<string>;

export function SubmitTask(arg1:string,arg2:boolean):Promise<string>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateModelPath(arg1:string):Promise<void>;

export function UpdateOpenAIKey(arg1:string):Promise<void>;

export function UpdateVaultPath(arg1:string):Promise<void>;
