// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckDependencies():Promise<main.DependencyStatus>;

export function GetConfig():Promise<config.Config>;

export function GetConfigPath():Promise<string>;

export function GetOllamaModels():Promise<Array<string>>;

export function SelectModelPath():Promise<string>;

export function SelectVaultPath():Promise<string>;

export function SubmitTask(arg1:string):Promise<string>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
