// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask() {
  return window['go']['main']['App']['CancelTask']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function SelectModelPath() {
  return window['go']['main']['App']['SelectModelPath']();
}

export function SelectVaultPath() {
  return window['go']['main']['App']['SelectVaultPath']();
}

export function SubmitTask(arg1, arg2) {
  return window['go']['main']['App']['SubmitTask'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
